on: push

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.8'
          - '3.9'
    name: Python ${{ matrix.python }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Setup Pipenv
        run: pipenv --python ${{ matrix.python }}

      - name: Install pip dependencies
        run: pipenv install --deploy --dev --pre

      - name: Check format
        run: pipenv run test-format

      - name: Unit test
        run: pipenv run test-unit

